export class Make {
  static readonly makes = new Map<string, string[]>([
    [
      'Audi',

      [
        'A1',
        'A2',
        'A3',
        'A4',
        'A5',
        'A6',
        'A6 e-tron',
        'A7',
        'A8',
        'R8',
        'Q2',
        'Q3',
        'Q4 e-tron',
        'Q5',
        'Q7',
        'Q8',
        'Q8 e-tron',
        'RS 2',
        'RS 3',
        'RS 4',
        'RS 5',
        'RS 6',
        'RS 7',
        'RS Q3',
        'RS Q8',
        'S1',
        'S2',
        'S3',
        'S4',
        'S5',
        'S6',
        'S7',
        'S8',
        'SQ2',
        'SQ5',
        'SQ7',
        'SQ8',
        'SQ8 e-tron',
        'TT',
        '100',
        '200',
        '50',
        '5000',
        '80',
        '90'
      ]
    ],

    [
      'BMW',

      [
        '1 series',
        '2 series',
        '3 series',
        '4 series',
        '5 series',
        '6 series',
        '7 series',
        '8 series',
        'i3',
        'i4',
        'i5',
        'i7',
        'i8',
        'iX',
        'iX1',
        'iX2',
        'iX3',
        'iX5',
        'M1',
        'M2',
        'M3',
        'M4',
        'M5',
        'M6',
        'M8',
        'X1',
        'X2',
        'X3',
        'X4',
        'X5',
        'X6',
        'X7',
        'XM',
        'X3M',
        'X4M',
        'X5M',
        'X6M',
        'Z1',
        'Z3',
        'Z4',
        'Z8'
      ]
    ],

    [
      'Mercedes-Benz',

      [
        'A Class',
        'B Class',
        'C Class',
        'E Class',
        'G Class',
        'S Class',
        'V Class',
        'AMG GT',
        'CLA',
        'CLC',
        'CLE',
        'CLK',
        'CLS',
        'EQA',
        'EQB',
        'EQC',
        'EQE',
        'EQG',
        'EQS',
        'EQV',
        'GLA',
        'GLB',
        'GLC',
        'GLE',
        'GLK',
        'GLS',
        'SL',
        'SLC',
        'SLK',
        'SLS AMG',
        'Vaneo',
        'Viano',
        'Vito'
      ]
    ],

    [
      'Porsche',

      [
        'Boxster',
        'Carrera GT',
        'Cayenne',
        'Cayman',
        'Macan',
        'Panamenra',
        'Taycan',
        '356',
        '718',
        '911',
        '912',
        '914',
        '917',
        '918',
        '924',
        '928',
        '944',
        '959',
        '968'
      ]
    ],

    [
      'Tesla',

      [
        'Cybertruck',
        'Model 3',
        'Model S',
        'Model X',
        'Model Y',
        'Roadster'
      ]
    ],

    [
      'Volvo',

      [
        'C30',
        'C40',
        'C70',
        'EX30',
        'EX90',
        'S40',
        'S60',
        'S70',
        'S80',
        'S90',
        'V40',
        'V50',
        'V60',
        'V70',
        'V90',
        'XC40',
        'XC60',
        'XC70',
        'XC90',
        '140',
        '164',
        '1800',
        '240',
        '260',
        '440 K',
        '460 L',
        '480 E',
        '66',
        '740',
        '760',
        '780 Bertone',
        '850',
        '940',
        '960'
      ]
    ],

  ]);
}
